DROP TABLE IF EXISTS PRODUCTEN;

CREATE TABLE PRODUCTEN (
id INT AUTO_INCREMENT  PRIMARY KEY,
 PRODUCT_NAME VARCHAR(250) NOT NULL,
 PRODUCT_DESCRIPTION VARCHAR(250) NOT NULL,

);

INSERT INTO PRODUCTEN (PRODUCT_NAME, PRODUCT_DESCRIPTION) VALUES
  ('Boek', 'Master your mindset'),
    ('Boek2', '2Master your mindset'),
   ('Boek3', '3Master your mindset');

